import { type Ease, getEasing } from "./easing";
import type { Keyframe, Value } from "./format/schema";
import { lerp } from "./math";

export interface Key {
  t: number;
  v: Value;
  ease?: Ease;
  /** Precomputed spline tangent(s) (value units per second) for numeric / vector keys. */
  m?: number[];
}

export type Track = Key[];

export interface TrackOptions {
  /**
   * Looping tracks compute tangents across the loop seam so cycles are seamless.
   * `duration` is the loop length.
   */
  loop?: { duration: number };
}

export function normalizeKey(k: Keyframe): Key {
  if (Array.isArray(k)) return { t: k[0], v: k[1], ease: k[2] as Ease | undefined };
  return { t: k.t, v: k.v, ease: k.ease as Ease | undefined };
}

const isVec2 = (v: Value): v is [number, number] => Array.isArray(v);
const isRecord = (v: Value): v is Record<string, number> =>
  typeof v === "object" && v !== null && !Array.isArray(v);

const components = (v: Value): number[] | null =>
  typeof v === "number" ? [v] : isVec2(v) ? [v[0], v[1]] : null;

/**
 * Monotone cubic (Fritsch–Carlson) tangents: smooth through every key, with no overshoot
 * past key values. Extremes and holds get zero tangents, so motion eases in and out of poses.
 */
function computeTangents(track: Track, opts: TrackOptions): void {
  const n = track.length;
  if (n < 2) return;
  const comps = track.map((k) => components(k.v));
  const dims = comps[0]?.length ?? 0;
  if (!dims || comps.some((c) => !c || c.length !== dims)) return;
  const loop = opts.loop;
  const seamless =
    loop !== undefined && comps[0]!.every((v, d) => Math.abs(v - comps[n - 1]![d]) < 1e-9) && track[0].t <= 1e-9;

  const tangents: number[][] = track.map(() => new Array(dims).fill(0));
  for (let d = 0; d < dims; d++) {
    const v = comps.map((c) => c![d]);
    const t = track.map((k) => k.t);
    const slope = (i: number) => (v[i + 1] - v[i]) / Math.max(1e-9, t[i + 1] - t[i]);
    const m = new Array(n).fill(0);
    for (let i = 0; i < n; i++) {
      let s0: number | undefined;
      let s1: number | undefined;
      if (i > 0) s0 = slope(i - 1);
      else if (seamless && n > 2) s0 = (v[n - 1] - v[n - 2]) / Math.max(1e-9, t[n - 1] - t[n - 2]);
      if (i < n - 1) s1 = slope(i);
      else if (seamless && n > 2) s1 = (v[1] - v[0]) / Math.max(1e-9, t[1] - t[0]);
      if (s0 === undefined || s1 === undefined) continue; // ends: ease in/out
      if (s0 * s1 <= 0) continue; // extreme or hold
      m[i] = (s0 + s1) / 2;
      // Fritsch–Carlson limiter (no overshoot).
      const a = m[i] / s0;
      const b = m[i] / s1;
      const h = a * a + b * b;
      if (h > 9) {
        const tau = 3 / Math.sqrt(h);
        m[i] = tau * (s0 + s1) / 2;
      }
    }
    for (let i = 0; i < n; i++) tangents[i][d] = m[i];
  }
  track.forEach((k, i) => (k.m = tangents[i]));
}

/** Normalizes keyframes, sorts them by time (stable) and precomputes spline tangents. */
export function normalizeTrack(keys: Keyframe[], opts: TrackOptions = {}): Track {
  const track = keys.map(normalizeKey).sort((a, b) => a.t - b.t);
  computeTangents(track, opts);
  return track;
}

/** Builds a track from already-normalized keys (e.g. generated by the script compiler). */
export function makeTrack(keys: Key[], opts: TrackOptions = {}): Track {
  const track = keys.map((k) => ({ t: k.t, v: k.v, ease: k.ease })).sort((a, b) => a.t - b.t);
  computeTangents(track, opts);
  return track;
}

const HEX = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i;

export function parseHex(c: string): [number, number, number] | null {
  if (!HEX.test(c)) return null;
  const h = c.length === 4 ? c.slice(1).split("").map((x) => x + x).join("") : c.slice(1);
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

const toHex = (rgb: number[]) => `#${rgb.map((v) => Math.round(Math.max(0, Math.min(255, v))).toString(16).padStart(2, "0")).join("")}`;

/** Linear RGB blend of two hex colors (returns `b` past the midpoint for non-hex colors). */
export function mixColor(a: string, b: string, t: number): string {
  const ca = parseHex(a);
  const cb = parseHex(b);
  if (!ca || !cb) return t >= 0.5 ? b : a;
  return toHex(ca.map((v, i) => lerp(v, cb[i], t)));
}

/**
 * Interpolates between two values. Hex colors blend smoothly; other non-numeric values step
 * (hold `a` until t reaches 1).
 */
export function interpolateValue(a: Value, b: Value, t: number): Value {
  if (typeof a === "number" && typeof b === "number") return lerp(a, b, t);
  if (typeof a === "string" && typeof b === "string" && HEX.test(a) && HEX.test(b)) return t >= 1 ? b : mixColor(a, b, t);
  if (isVec2(a) && isVec2(b)) return [lerp(a[0], b[0], t), lerp(a[1], b[1], t)];
  if (isRecord(a) && isRecord(b)) {
    const out: Record<string, number> = {};
    for (const k of new Set([...Object.keys(a), ...Object.keys(b)])) {
      out[k] = lerp(a[k] ?? 0, b[k] ?? 0, t);
    }
    return out;
  }
  return t >= 1 ? b : a;
}

function hermite(p0: number, p1: number, m0: number, m1: number, span: number, u: number): number {
  const u2 = u * u;
  const u3 = u2 * u;
  return (
    (2 * u3 - 3 * u2 + 1) * p0 + (u3 - 2 * u2 + u) * m0 * span + (-2 * u3 + 3 * u2) * p1 + (u3 - u2) * m1 * span
  );
}

/**
 * Samples a track at time `t`. Returns `undefined` for an empty track.
 * Segments whose arriving key has no `ease` use smooth spline interpolation ("auto");
 * an explicit `ease` (including `linear`) overrides it.
 */
export function sampleTrack(track: Track, t: number): Value | undefined {
  const n = track.length;
  if (n === 0) return undefined;
  if (t <= track[0].t) return track[0].v;
  if (t >= track[n - 1].t) return track[n - 1].v;
  let lo = 0;
  let hi = n - 1;
  while (hi - lo > 1) {
    const mid = (lo + hi) >> 1;
    if (track[mid].t <= t) lo = mid;
    else hi = mid;
  }
  const a = track[lo];
  const b = track[hi];
  const span = b.t - a.t;
  if (span <= 0) return b.v;
  const u = (t - a.t) / span;
  if (b.ease === undefined && a.m && b.m) {
    if (typeof a.v === "number" && typeof b.v === "number") return hermite(a.v, b.v, a.m[0], b.m[0], span, u);
    if (isVec2(a.v) && isVec2(b.v)) {
      return [hermite(a.v[0], b.v[0], a.m[0], b.m[0], span, u), hermite(a.v[1], b.v[1], a.m[1], b.m[1], span, u)];
    }
  }
  const eased = b.ease === undefined ? getEasing("sineInOut")(u) : getEasing(b.ease)(u);
  return interpolateValue(a.v, b.v, eased);
}

/** Last key time of a track (0 if empty). */
export const trackEnd = (track: Track): number => (track.length ? track[track.length - 1].t : 0);
